### ISSUE TITLE
Contare la lingua di compilazione

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#23]
Ricordarsi di segnare la lingua usata dall'utente per compilare (ita, eng o fur) e di riportare il dato nei report

**Comment by paolini** [comment]
La lingua viene già memorizzata. Nel report mettiamo un diagramma a torta oppure una tabella con la percentuale delle tre lingue?

**Comment by matteo-fogale** [comment]
Mettiamo un diagramma a torta che così cambiamo un po' ;-)
