### ISSUE TITLE
vista con link nascosto per visualizzazione questionari della scuola

### ISSUE THREAD

**Issue by paolini** [paolini/scandai#26]
* visualizzazione report singole classi
* visualizzazione report globale

**Comment by matteo-fogale** [comment]
Forse la soluzione più semplice sarebbe rendere condivisibile e gestibile la pagina per l'insegnante del quesionario di una classe tramite un link (senza autenticazione). Così admin crea il questionario, condivide tranite link con il somministratore la pagina dove c'è l'url e il qr da condividere con la classe. Il somministratore chiude il questionario una volta completato e può visualizzare e stampare il report. Parallelamente possiamo mantenere anche il meccanismo di accreditamento così come lo abbiamo già implementato (a parte la semplificazione della pagina di accesso). Fattibile?

**Comment by paolini** [comment]
dovrebbe essere a posto
