### ISSUE TITLE
Cancellazione dei questionari di prova 

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#28]
Per iniziare la fotografia linguistica vera e propria è necessario cancellare i questionari di prova che abbiamo creato. In questo momento admin non può cancellare questionari che abbiano dei dati (può cancellare solo i questionari chiusi e senza risposte). Forse admin dovrebbe poter cancellare qualsiasi questionario (ma non ne sono sicuro). Ad ogni modo bisogna trovare un modo per pulire il database prima di iniziare davvero.

**Comment by paolini** [comment]
Possiamo fare in modo che la cancellazione si può fare se il numero di risposte è inferiore ad una soglia. Ci metto 10 e poi eventualmente si cambia.

**Comment by matteo-fogale** [comment]
Ok, mi sembra una ottima soluzione
