### ISSUE TITLE
Controllo accesso accreditamento

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#29]
Ciao, se cerco di accedere con fogale.matteo@liceocopernico.org col meccanismo di accreditamento vi aemail, non arriva l'email. Credo che la mia scuola abbia un blocco sulla posta in ingresso di qualche tipo, ed è possibile che la stessa cosa succeda anche con altre scuole. Non è un problema urgnete, ma ci dovremo pensare.

**Comment by paolini** [comment]
Non era configurato il From. Ora dovrebbe funzionare.

**Comment by matteo-fogale** [comment]
ora funziona perfettamente ;-)
