### ISSUE TITLE
visualizzazione dati per scuola

### ISSUE THREAD

**Issue by paolini** [paolini/scandai#30]
* un link da condividere con tutti i docenti per visualizzare i report della scuola
* il link (segreto) viene creato da admin nella pagina della scuola

**Comment by matteo-fogale** [comment]
Aggiungo alcuni dettagli che mi sono dimenticato nel meet di prima (vedi se possono avere senso):
- nella pagina di visualizzazione della singola scuola deve essere possibile anche accedere ai report delle singole classi
- tutti i report (sia  quello della scuola, che quelli delle classi) devono avere il pulsante di stampa pdf
