### ISSUE TITLE
Scelta lingua di compilazione

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#33]
Cambiare la modalità di scelta (senza opzione predefinita sull'italiano)

**Comment by paolini** [comment]
Però il resto della pagina in che lingua è scritto? Facciamo che non compare niente finché non scegli la lingua?

**Comment by paolini** [comment]
Prova a vedere se così va bene...

**Comment by matteo-fogale** [comment]
Mi sembra tutto ok. Se ritieni che si possa riportare su foto.lavplu si può procedere. Inviato da Posta per Windows Da: Emanuele PaoliniInviato: sabato 23 settembre 2023 19:08A: paolini/scandaiCc: Matteo Fogale; AuthorOggetto: Re: [paolini/scandai] Scelta lingua di compilazione (Issue #33) Prova a vedere se così va bene...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
