### ISSUE TITLE
Proposta di modifica del calcolo dei valori medi di competenza lingue

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#38]
Un collega del gruppo di coordinamento avanza la seguente proposta (mi piacerebbe discuterla con te però prima di procedere a eventuali midifiche).

****
I "valori medi delle competenze valutate" o crôt ch'a laressin calcolâts sul numar di chei ch'a declarin di fevelâ chê lenghe. Se di no la misure e ven fûr sbalade (prove cjale al Copernico une lenghe che no sedin chês plui feveladis).

**Comment by paolini** [comment]
Significa scorporare dal denominatore chi ha messo 0.

**Comment by paolini** [comment]
fatto in versione 1.2.6
