### ISSUE TITLE
Consultazione Database: Aggiungere testo della fotografia

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#57]
Per gli utenti visualizzatori del database, aggiungere la possibilità di visualizzare la lista delle domande della fotografia linguistica (come fare?)

**Comment by paolini** [comment]
Può andar bene una versione "readonly" del questionario? Così uno vede esattamente quello che vedono gli studenti. Solo che per leggere tutte le domande bisogna scorrere le pagine...

**Comment by matteo-fogale** [comment]
La versione "Readonly" va bene. Potremmo fare in modo che si apra su un'altra scheda del browser. E' anche importante che, nel caso un domani ci sia una modifica alle domande, il sistema si aggiorni da solo.

**Comment by paolini** [comment]
fatto
