### ISSUE TITLE
traduzioni

### ISSUE THREAD

**Issue by paolini** [paolini/scandai#60]
Tradurre:

* "breve" e "completo" nei nomi dei questionari pagina "/"
* "questionari chiusi" pagina "/"
* "utente" pagina "/"

**Comment by matteo-fogale** [comment]
Proposta: traduciamo tutto (anche le pagine di amministrazione). Sarebbe possibile separare le stringhe delle pagine di amministrazione da quelle delle pagine utente in qualche modo?
Altra cosetta: sarebbe possibile marcare con un colore diverso le pagine di amministrazione nel menù in alto (così uno a più il polso di chi vede cosa)?

**Comment by paolini** [comment]
Le traduzioni dei nomi dei questionari "breve" e "completo" vanno tradotti modificando il file /lib/questionary.ts alla riga 545 e alla riga 865.

**Comment by paolini** [comment]
Ci sono un po' di stringhe da tradurre... ti assegno la issue!

**Comment by matteo-fogale** [comment]
Stringhe tradotte ;-)
