### ISSUE TITLE
Campione variabile nelle domande

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#62]
Nelle domande non obbligatorie: calcolare il valore del campione (cioè il numero di quelli che hanno risposto a quella domanda) e visualizzarlo nel report. Calcolare inoltre le percentuali rispetto al campione di quella domanda e non al campione totale (cioè numero di quelli ai quali è stata somministrata la fotografia).

**Comment by paolini** [comment]
Fatto ora su develop. @matteo-fogale dacci un'occhiata.

**Comment by matteo-fogale** [comment]
Mi sembra ok, solo due cose: a) bisogna migliorare l'impaginazione, eviterei il grassetto e la scrittura in colonne. Sarebbe anche possibile usare un font più piccolo rispetto a quello standard del report? (come se fosse una nota ai dati riportati). b) non trovo le stringhe da tradurre nel file translations.js ... puoi aggiungerle che allineo la traduzione fur e eng?

**Comment by paolini** [comment]
fatto, vedi ora.

**Comment by matteo-fogale** [comment]
Mi sembra funzioni tutto. Ho fatto le traduzioni, imaginazione ok. Unico problema: non capisco come calcola la voce "numero di risposte" credo ci sia un errore di calcolo puoi controllare?

**Comment by paolini** [comment]
Ogni studente può dare più di una risposta, quindi il "numero risposte" può essere maggiore del numero di questionari.

**Comment by matteo-fogale** [comment]
Ottimo, mi sembra le due modifiche funzionino puoi fare il port sulla versione di produzione? (chiudo anche le issues relative)
________________________________
Da: Emanuele Paolini ***@***.***>
Inviato: sabato 10 febbraio 2024 09:18
A: paolini/scandai ***@***.***>
Cc: Matteo Fogale ***@***.***>; Mention ***@***.***>
Oggetto: Re: [paolini/scandai] Campione variabile nelle domande (Issue #62)


Ogni studente può dare più di una risposta, quindi il "numero risposte" può essere maggiore del numero di questionari.
