### ISSUE TITLE
nome del link di somministrazione

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#78]
Cambiare nome (anche nelle versioni localizzate) al link di somministrazione.
"link di somministrazione" diventa "link di amministrazione"

**Comment by paolini** [comment]
Ho fatto le traduzioni in italiano. Vanno fatte le altre lingue: [https://github.com/paolini/scandai/edit/develop/lib/translations.js](https://github.com/paolini/scandai/edit/develop/lib/translations.js)

**Comment by matteo-fogale** [comment]
Traduzioni aggiunte
