### ISSUE TITLE
Statistiche su uso esclusivo di una lingua

### ISSUE THREAD

**Issue by matteo-fogale** [paolini/scandai#83]
Come si possono separare i dati sui monolingui? Ci pensiamo, questo è solo un promemoria

**Comment by matteo-fogale** [comment]
Forse si potrebbe aggiungere una voce nella tabella sotto il grafico in tutte le risposte che prevedono una selezione multipla non esclusiva di una lingua. Nella tabella sottostante inserirei due righe: uso esclusivo (%) e uso esclusivo (conteggio) che contano per ogni colonna relativa alla lingua quanti questionari hanno selzionato SOLO quella lingua nella risposta.

**Comment by paolini** [comment]
![image](https://github.com/user-attachments/assets/2b0ffbb1-0885-48c9-a456-5ef37b049172)

**Comment by matteo-fogale** [comment]
Ok cambierei la scritta "monolingue" con "uso esclusivo". Sotto aggiungerei una riga che calcola la percentuale delle risposte con uso esclusivo. Toglierei invece la riga "risposte" anche perché non mi è chiaro quale sia la sua funzione.
